import type { C4Model } from "./types";

/**
 * C4_MODEL — extracted from roms-c4-architecture.html
 * Contains SYSTEM, CONTAINERS (8), and COMPONENTS (for web, api, int containers).
 */
export const C4_MODEL: C4Model = {
  system: {
    name: "ROMS",
    fullName: "Research Operations Management System",
    desc: "A unified digital platform that orchestrates all 10 domains of biomedical & life-science research operations — from biospecimen management and data capture to regulatory compliance and grant finance.",
    tech: "Web Application / SaaS",
    users: [
      { icon: "👩‍🔬", name: "Laboratory Scientists", desc: "Manage samples, experiments, assays, and instrument workflows" },
      { icon: "📋", name: "Data Managers", desc: "Capture, validate, and govern research data across studies" },
      { icon: "👔", name: "Research Administrators", desc: "Oversee HR, finance, grants, and regulatory submissions" },
      { icon: "🏛️", name: "Principal Investigators", desc: "Monitor study progress, budgets, and compliance across domains" },
      { icon: "🛡️", name: "Quality & Compliance Officers", desc: "Manage SOPs, audits, CAPA, and regulatory filings" },
      { icon: "👥", name: "Community Engagement Staff", desc: "Recruit, consent, and retain study participants" },
    ],
    externals: [
      { icon: "🏥", name: "REDCap / EDC", desc: "Electronic Data Capture platform for clinical data", tech: "REDCap / OpenClinica" },
      { icon: "🧬", name: "LIMS", desc: "Laboratory Information Management System for sample tracking", tech: "LabVantage / STARLIMS" },
      { icon: "📡", name: "ELN", desc: "Electronic Lab Notebook for raw experimental data", tech: "Benchling / LabArchives" },
      { icon: "💳", name: "Financial ERP", desc: "Institutional enterprise resource planning for finance", tech: "SAP / QuickBooks" },
      { icon: "🏛️", name: "Ethics Portal", desc: "IRB/REC submission and approval tracking", tech: "iRIS / Cayuse" },
      { icon: "🌐", name: "Regulatory Registries", desc: "Clinical trial registration databases", tech: "ClinicalTrials.gov / PACTR" },
      { icon: "📦", name: "Procurement System", desc: "Purchase orders, vendors, and goods receipt", tech: "SAP MM / Coupa" },
      { icon: "☁️", name: "HPC / Cloud", desc: "High-performance compute for bioinformatics pipelines", tech: "AWS / Azure / On-Prem HPC" },
    ],
  },
  containers: [
    {
      id: "web",
      icon: "🌐",
      name: "Web Application",
      kind: "Container",
      tech: "React + TypeScript",
      color: "con",
      desc: "Single-page application serving all 10 ROMS domain UIs. Role-based views render the appropriate domain modules per user.",
      responsibilities: [
        "Domain navigation and three-panel UI",
        "Role-based access rendering",
        "Real-time form validation",
        "Dark/light theme and responsive layout",
      ],
      drillTo: 3,
    },
    {
      id: "api",
      icon: "⚙️",
      name: "API Gateway & Backend",
      kind: "Container",
      tech: "Node.js / REST + GraphQL",
      color: "con",
      desc: "Stateless API layer handling all business logic, data transformations, and cross-domain orchestration.",
      responsibilities: [
        "Authentication & authorisation (OAuth2/JWT)",
        "Domain service routing",
        "Audit trail generation",
        "Integration orchestration",
      ],
      drillTo: 3,
    },
    {
      id: "db",
      icon: "🗄️",
      name: "Core Database",
      kind: "Container",
      tech: "PostgreSQL + TimescaleDB",
      color: "con",
      desc: "Primary relational store for all ROMS transactional data including samples, SOPs, HR records, finance, and participant data.",
      responsibilities: [
        "Multi-tenant data isolation",
        "ALCOA+ audit columns on all tables",
        "Time-series for temperature/sensor data",
        "GDPR-compliant data partitioning",
      ],
      drillTo: null,
    },
    {
      id: "docstore",
      icon: "📂",
      name: "Document Store",
      kind: "Container",
      tech: "S3-compatible Object Storage",
      color: "con",
      desc: "Stores all binary assets: SOP PDFs, consent form scans, raw instrument data files, ELN attachments, and TMF documents.",
      responsibilities: [
        "Versioned document storage",
        "Controlled copy distribution",
        "Encrypted at-rest storage",
        "Retention policy enforcement",
      ],
      drillTo: null,
    },
    {
      id: "notify",
      icon: "🔔",
      name: "Notification Service",
      kind: "Container",
      tech: "Event Bus + Email/SMS",
      color: "con",
      desc: "Asynchronous notification engine dispatching alerts for temperature excursions, expiry warnings, CAPA deadlines, and audit reminders.",
      responsibilities: [
        "Email & SMS dispatch",
        "In-app notification feed",
        "Escalation rules engine",
        "Alert audit logging",
      ],
      drillTo: null,
    },
    {
      id: "iot",
      icon: "📡",
      name: "IoT Integration Layer",
      kind: "Container",
      tech: "MQTT Broker + Stream Processor",
      color: "con",
      desc: "Ingests real-time sensor streams from cold-chain monitors, biosafety systems, and laboratory environment sensors.",
      responsibilities: [
        "MQTT message ingestion",
        "Temperature excursion detection",
        "Time-series storage pipeline",
        "Sensor health monitoring",
      ],
      drillTo: null,
    },
    {
      id: "auth",
      icon: "🔒",
      name: "Identity & Access",
      kind: "Container",
      tech: "Keycloak / OAuth2 + RBAC",
      color: "con",
      desc: "Manages authentication, role-based access control, and SSO across all ROMS modules and integrated systems.",
      responsibilities: [
        "SSO with institutional IdP",
        "Role & permission management",
        "MFA enforcement",
        "Session and token lifecycle",
      ],
      drillTo: null,
    },
    {
      id: "int",
      icon: "🔗",
      name: "Integration Hub",
      kind: "Container",
      tech: "REST / HL7 FHIR / APIs",
      color: "con",
      desc: "Mediates data exchange between ROMS and external systems including LIMS, EDC, ERP, ethics portals, and regulatory registries.",
      responsibilities: [
        "Bi-directional LIMS sync",
        "REDCap data push/pull",
        "Financial ERP posting",
        "Ethics portal status polling",
      ],
      drillTo: 3,
    },
  ],
  components: {
    web: [
      { icon: "🧬", name: "Biospecimen Module", kind: "Component", tech: "React", color: "cmp", desc: "Three-panel UI for sample collection, processing, storage mapping, and retrieval workflows." },
      { icon: "📊", name: "Data Management Module", kind: "Component", tech: "React + REDCap Embed", color: "cmp", desc: "CRF design, EDC data entry, query management, and database lock workflows." },
      { icon: "📄", name: "QMS / SOP Module", kind: "Component", tech: "React", color: "cmp", desc: "Document authoring, version control, training assignment, and audit management." },
      { icon: "💰", name: "Finance Module", kind: "Component", tech: "React", color: "cmp", desc: "Grant pre/post-award dashboards, budget tracking, funder report generation." },
      { icon: "🛡️", name: "Regulatory Module", kind: "Component", tech: "React", color: "cmp", desc: "Ethics submissions, protocol tracking, SAE reporting, and TMF management." },
      { icon: "👥", name: "Participant Module", kind: "Component", tech: "React", color: "cmp", desc: "Recruitment tracking, consent management, scheduling, and CAB coordination." },
      { icon: "👤", name: "HR Module", kind: "Component", tech: "React", color: "cmp", desc: "Staff onboarding, training records, competency assessments, and scheduling." },
      { icon: "📦", name: "Inventory Module", kind: "Component", tech: "React", color: "cmp", desc: "Reagent stock, equipment register, procurement workflows, and waste records." },
      { icon: "🧪", name: "Lab Workflow Module", kind: "Component", tech: "React", color: "cmp", desc: "Protocol tracking, instrument booking, result capture, and batch management." },
      { icon: "📡", name: "Infrastructure Module", kind: "Component", tech: "React", color: "cmp", desc: "Platform admin, IoT monitoring dashboards, HPC job tracking, and IT support." },
    ],
    api: [
      { icon: "🔐", name: "Auth Service", kind: "Component", tech: "Node.js", color: "cmp", desc: "Validates JWT tokens, enforces RBAC policies, and manages session state." },
      { icon: "📋", name: "Domain Service Router", kind: "Component", tech: "Node.js", color: "cmp", desc: "Routes API calls to appropriate domain microservice handlers." },
      { icon: "🔎", name: "Audit Trail Engine", kind: "Component", tech: "Node.js + PostgreSQL", color: "cmp", desc: "Captures all data mutations with user, timestamp, before/after values for ALCOA+ compliance." },
      { icon: "📤", name: "Report Generator", kind: "Component", tech: "Node.js + PDF/Excel", color: "cmp", desc: "Generates funder reports, financial statements, QC summaries, and regulatory filings." },
      { icon: "🔁", name: "Workflow Engine", kind: "Component", tech: "Node.js + BullMQ", color: "cmp", desc: "Manages multi-step approval workflows: SOP sign-off, CAPA actions, consent processes." },
    ],
    int: [
      { icon: "🧬", name: "LIMS Connector", kind: "Component", tech: "REST / HL7 FHIR", color: "cmp", desc: "Synchronises sample metadata and result data between ROMS and the institution's LIMS." },
      { icon: "📋", name: "REDCap Connector", kind: "Component", tech: "REDCap API", color: "cmp", desc: "Pushes CRF definitions to REDCap and pulls completed records back into ROMS." },
      { icon: "💳", name: "ERP Connector", kind: "Component", tech: "SAP BAPI / REST", color: "cmp", desc: "Posts purchase orders, grant journal entries, and cost allocations to the financial ERP." },
      { icon: "🏛️", name: "Ethics Portal Connector", kind: "Component", tech: "REST / iRIS API", color: "cmp", desc: "Submits ethics applications and polls approval status from the institutional REC portal." },
      { icon: "🌐", name: "Registry Connector", kind: "Component", tech: "ClinicalTrials.gov API", color: "cmp", desc: "Registers and updates clinical trials on ClinicalTrials.gov, PACTR, and ISRCTN." },
    ],
  },
};

// Relationship data for C2 diagram
export const C4_RELATIONSHIPS = [
  { from: "Laboratory Scientists", arrow: "→", to: "ROMS", label: "Submit samples, log experiments, run assays" },
  { from: "Data Managers", arrow: "→", to: "ROMS", label: "Capture and validate study data via EDC/ELN" },
  { from: "Research Administrators", arrow: "→", to: "ROMS", label: "Manage HR, grants, SOPs, and regulatory filings" },
  { from: "ROMS", arrow: "→", to: "REDCap / EDC", label: "Push CRF definitions; pull completed data records" },
  { from: "ROMS", arrow: "→", to: "LIMS", label: "Sync sample metadata and assay result data" },
  { from: "ROMS", arrow: "→", to: "Financial ERP", label: "Post purchase orders and grant journal entries" },
  { from: "ROMS", arrow: "→", to: "Ethics Portal", label: "Submit IRB applications and retrieve approval status" },
  { from: "ROMS", arrow: "→", to: "Regulatory Registries", label: "Register and update clinical trials" },
  { from: "IoT Sensors", arrow: "→", to: "ROMS", label: "Stream real-time temperature and environmental data" },
] as const;

export const C4_CONTAINER_INTERACTIONS = [
  { from: "Web App", arrow: "→", to: "API Gateway", label: "HTTPS/REST + GraphQL — all domain operations" },
  { from: "API Gateway", arrow: "→", to: "Core Database", label: "SQL — reads/writes all transactional domain data" },
  { from: "API Gateway", arrow: "→", to: "Document Store", label: "S3 API — stores and retrieves SOP PDFs and raw data files" },
  { from: "API Gateway", arrow: "→", to: "Notification Service", label: "Internal events — triggers alerts and reminders" },
  { from: "API Gateway", arrow: "→", to: "Integration Hub", label: "Internal API — routes data to/from external systems" },
  { from: "IoT Layer", arrow: "→", to: "Core Database", label: "Time-series writes — temperature and sensor readings" },
  { from: "IoT Layer", arrow: "→", to: "Notification Service", label: "Excursion events — cold-chain and safety alerts" },
  { from: "Identity & Access", arrow: "→", to: "Web App", label: "OAuth2 tokens — authenticates and authorises all users" },
  { from: "Identity & Access", arrow: "→", to: "API Gateway", label: "JWT validation — enforces RBAC on every request" },
  { from: "Integration Hub", arrow: "→", to: "REDCap / LIMS / ERP", label: "REST / HL7 FHIR — bi-directional data exchange" },
] as const;
